AWSTemplateFormatVersion: 2010-09-09

Outputs:

  LambdaArn: !Ref Lambda.Arn

Resources:

  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      Code: src/
      Handler: main.lambda_handler
      Role: !GetAtt Role.Arn
      Runtime: python3.7

  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
