AWSTemplateFormatVersion: 2010-09-09

Parameters:

  Bucket:
    Type: String

  Key:
    Type: String

Resources:

  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: cf-example-1
      Code:
        S3Bucket: !Ref Bucket
        S3Key: !Ref Key
      Handler: main.lambda_handler
      Role: !GetAtt Role.Arn
      Runtime: python3.7

  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
